

import json
import os

import pandas as pd

CACHE = "raw_cache.csv"
OUT = "p5_data.js"
N_TYPES = 10

if not os.path.exists(CACHE):
    raise SystemExit(f"can't find {CACHE}，run again nyc311_more.py")

print("reading…")
df = pd.read_csv(CACHE)

df["created_date"] = pd.to_datetime(df["created_date"], errors="coerce")
df = df.drop_duplicates(subset="unique_key")
df = df[df["created_date"].notna()]

df["complaint_type"] = df["complaint_type"].str.strip().str.title()
df["weekday"] = df["created_date"].dt.day_name()
df["hour"] = df["created_date"].dt.hour

print(f"after clean {len(df):,} rows")

WEEKDAYS = ["Monday", "Tuesday", "Wednesday", "Thursday",
            "Friday", "Saturday", "Sunday"]

# ---------------------------------------------------------------
# assembly
# ---------------------------------------------------------------


def grid(sub):
    """change a group in to 7*24 percent matrix"""
    counts = sub.groupby(["weekday", "hour"]).size()
    total = len(sub)
    out = []
    for wd in WEEKDAYS:
        row = []
        for hr in range(24):
            n = int(counts.get((wd, hr), 0))
            row.append(round(n / total * 100, 4) if total else 0.0)
        out.append(row)
    return out


data = {"All complaints": grid(df)}
totals = {"All complaints": len(df)}

top = df["complaint_type"].value_counts().head(N_TYPES)
for name in top.index:
    sub = df[df["complaint_type"] == name]
    data[name] = grid(sub)
    totals[name] = int(len(sub))

# ---------------------------------------------------------------
# writing files
# ---------------------------------------------------------------

order = ["All complaints"] + list(top.index)

with open(OUT, "w", encoding="utf-8") as f:
    f.write("// NYC 311 · March 2024 · generated by make_p5_data.py\n")
    f.write("// DATA[type][weekday 0-6 = Mon-Sun][hour 0-23] = % of that type's month\n\n")
    f.write("const TYPES = " + json.dumps(order, ensure_ascii=False) + ";\n\n")
    f.write("const TOTALS = " + json.dumps(totals, ensure_ascii=False) + ";\n\n")
    f.write("const DATA = " + json.dumps(data, ensure_ascii=False) + ";\n")

size = os.path.getsize(OUT) / 1024
print(f"\nfinsh wrting{OUT}（{size:.0f} KB，{len(order)} catrgories）")

print("\monthly total amount of each type：")
for name in order:
    print(f"  {name:<28} {totals[name]:>8,}")

print("\npeak hours of each type：")
for name in order:
    g = data[name]
    best = max(
        ((g[w][h], w, h) for w in range(7) for h in range(24)),
        key=lambda t: t[0],
    )
    print(f"  {name:<28} {WEEKDAYS[best[1]]:<10} {best[2]:>2}:00   {best[0]:.2f}%")
